Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  #config.vm.box_version = "20220916.0.0"
  config.vm.hostname = "ubuntu"
  # require plugin https://github.com/leighmcculloch/vagrant-docker-compose
  config.vagrant.plugins = "vagrant-docker-compose"
  
  #vagrant-vbguest is a Vagrant plugin which automatically installs the host's VirtualBox Guest Additions on the guest system.
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  # install docker and docker-compose
  config.vm.provision :docker
  config.vm.provision :docker_compose
  
  config.vm.provision "shell",
    inline: "timedatectl set-timezone America/Argentina/Buenos_Aires",
    run: "always"     
    
  config.vm.provision :shell, path: "update.sh"
  config.vm.provision :shell, path: "cleanup.sh"
  #config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8300, host: 8300
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
	vb.customize ["modifyvm", :id, "--chipset", "ich9"]  
    vb.customize ["modifyvm", :id, "--name", "ubuntu-18.04"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

end
