name: Styling

on:
  push:
    branches: [ rel-700 ]
  pull_request:
    branches: [ rel-700 ]

jobs:

  php_styling:
    runs-on: ubuntu-20.04
    name: PHP
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Report PHP Version
        run: php -v

      - name: Install php_codesniffer
        run: |
          failTest=false
          composer global require "squizlabs/php_codesniffer=3.*" || failTest=true
          if $failTest; then
            exit 1
          fi

      - name: Check PHP Styling
        run: |
          failTest=false
          $HOME/.composer/vendor/bin/phpcs -p -n --extensions=php,inc --report-width=120 --standard=ci/phpcs.xml --report=full . || failTest=true
          if $failTest; then
            exit 1
          fi

  css_styling:
    runs-on: ubuntu-20.04
    name: CSS
    steps:
      - uses: actions/checkout@v2

      - name: Install npm package
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: npm install
        run: |
          failTest=false
          npm install || failTest=true
          if $failTest; then
            exit 1
          fi

      - name: Check CSS Styling
        run: |
          failTest=false
          npx stylelint "**/*.css" || failTest=true
          npx stylelint "**/*.scss" || failTest=true
          if $failTest; then
            exit 1
          fi
