# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu1804"
  
    config.vm.network "private_network", ip: "192.168.56.100"
    # config.vm.network "forwarded_port", guest:80, host: 8080, auto_correct: true
    config.vm.provider "virtualbox" do |vb|
      vb.name = "nodejs-box"
      vb.memory = "512"
    end
  
    config.vm.synced_folder "./basic-nodejs", "/home/vagrant/basic-nodejs"
  
    config.vm.provision "install-node", type: "shell", privileged: false do |s|
      s.path = "./install-node.sh"
    end
  
  end